package problem.h000.d040;

import problem.Problem;
import util.Numbers;

/**
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 * <p>
 * Triangle 	  	Tn=n(n+1)/2 	1, 3, 6, 10, 15, ...<br/>
 * Pentagonal 	Pn=n(3n?1)/2 	1, 5, 12, 22, 35, ...<br/>
 * Hexagonal 	  	Hn=n(2n?1) 	  	1, 6, 15, 28, 45, ...<br/>
 * <p>
 * It can be verified that T285 = P165 = H143 = 40755.
 * <p>
 * Find the next triangle number that is also pentagonal and hexagonal.
 */
public class Problem045 implements Problem{
    @Override
    public long solve() {
        long result;

        for (long n = 144; ; n++) {
            long hexagonal = n * (2 * n - 1);
            boolean isPentagonal = Numbers.hasNaturalRoot(3, -1, -2 * hexagonal);
            boolean isTriangle = Numbers.hasNaturalRoot(1, 1, -2 * hexagonal);

            if (isPentagonal && isTriangle) {
                result = hexagonal;
                break;
            }
        }

        return result;
    }

    public static void main(String[] args) {
        System.out.println(new Problem045().solve());
    }
}
